# p1as-cluster-tools values

# ingress-nginx-public values
ingress-nginx-public:
  ingress-nginx:
    controller:
      serviceAccount:
        annotations:
          ${IRSA_INGRESS_ANNOTATION_KEY_VALUE}
      service:
        annotations:
          ${NLB_NGX_PUBLIC_ANNOTATION_KEY_VALUE}
      autoscaling:
        minReplicas: 4
        maxReplicas: 6
        targetCPUUtilizationPercentage: 50
      extraContainers:
        - name: sigsci-agent
          env:
            - name: AWS_REGION
              value: ${REGION}
            - name: ENVIRONMENT_PREFIX
              value: ${ENVIRONMENT_PREFIX}

# ingress-nginx-private values
ingress-nginx-private:
  ingress-nginx:
