kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# Apply PingAccess-WAS runtime engine deployment resources
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingaccess-was/engine?ref=${K8S_GIT_BRANCH}

images:
- name: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingaccess-was${ECR_ENV}
  newName: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingaccess-was${ECR_ENV}
  newTag: ${PINGACCESS_WAS_IMAGE_TAG}

patchesJson6902:

### PingAccess WAS Engine Last Update Config Map ###
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pingaccess-was
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: pingaccess-was-last-update-config

### Ingress patches ###

### Separated Ingresses through PA-WAS engines ###

# Argo CD
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: argocd-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: argocd.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: argocd.${TENANT_DOMAIN}
